CREATE TABLE place_listings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    place_type VARCHAR2(50) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    phone VARCHAR2(30),
    website VARCHAR2(255),
    user_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT place_listings_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id)
                            );