CREATE TABLE event_listings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    event_type VARCHAR2(50) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_id NUMBER(19) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    CONSTRAINT event_listings_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id));