CREATE TABLE community_posts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_id NUMBER(19) NOT NULL,  CONSTRAINT community_posts_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id)
                             );