CREATE TABLE comments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_id NUMBER(19) NOT NULL,
    community_post_id NUMBER(19) NOT NULL,
    CONSTRAINT comments_community_posts_id_fk
        FOREIGN KEY (community_post_id) REFERENCES community_posts(id),
    CONSTRAINT comments_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id)
                      );