CREATE TABLE market_listings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    unit VARCHAR2(10),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_id NUMBER(19) NOT NULL,
    CONSTRAINT market_listings_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id));