CREATE TABLE craft_listings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    price NUMBER(10,2),
    material VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_id NUMBER(19) NOT NULL,
    is_customizable NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT craft_listings_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT craft_listings_is_customizable_ck
        CHECK (is_customizable IN (0,1))
                            );