spring:
  application:
    name: zemyanadlan-backend

  profiles:
    active: local

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #change to 300 - 5m
    refreshTokenExpiration: 604800 #7d