spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zemyanadlan?createDatabaseIfNotExist=true
    username: zemya
    password: zemya123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true