ALTER TABLE community_posts
ADD COLUMN post_type VARCHAR(20) NOT NULL,
ADD COLUMN views_count INT NOT NULL DEFAULT 0,
ADD COLUMN comments_count INT NOT NULL DEFAULT 0,
ADD COLUMN likes_count INT NOT NULL DEFAULT 0,
ADD COLUMN thumbnail_url VARCHAR(255);